"""images table

Revision ID: 90076fa54779
Revises: afb25bec1f7c
Create Date: 2018-06-29 17:46:04.545038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90076fa54779'
down_revision = 'afb25bec1f7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_contents', sa.Column('data', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_contents', 'data')
    # ### end Alembic commands ###
